# Generated by Django 2.1.7 on 2019-02-27 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(0, 'Женский'), (1, 'Мужской')], default=0)),
                ('cp', models.IntegerField(choices=[(1, 'Типичная стенокардия'), (2, 'Атипичная стенокардия'), (3, 'Отсутсвие стенокардии'), (4, 'Отсутсвие симптомов')], default=1)),
                ('resting_bp', models.IntegerField()),
                ('serum_cholesterol', models.IntegerField()),
                ('fasting_blood_sugar', models.IntegerField(choices=[(1, 'да'), (2, 'нет')], default=0)),
                ('resting_ecg', models.IntegerField(choices=[(0, 'Норма'), (1, 'Наличие аномалии зубца ST-T'), (2, 'Гипертрофия')], default=0)),
                ('max_heart_rate', models.IntegerField()),
                ('exercise_induced_angina', models.IntegerField(choices=[(0, 'Нет'), (1, 'Да')], default=0)),
                ('st_depression', models.DecimalField(decimal_places=2, max_digits=4)),
                ('st_slope', models.IntegerField(choices=[(1, 'Нарастающий'), (2, 'Ровный'), (3, 'Понижающий')])),
                ('number_of_vessels', models.IntegerField(choices=[(0, 'Нет'), (1, 'Один'), (2, 'Два'), (3, 'Три')])),
                ('thallium_scan_results', models.IntegerField(choices=[(3, 'Норма'), (6, 'Исправлен дефект'), (7, 'Обратимый дефект')])),
                ('predicted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('num', models.IntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predict', to='accounts.UserProfileInfo')),
            ],
        ),
    ]
